FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:0.5.29 /uv /uvx /bin/

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

COPY apps/api/pyproject.toml ./pyproject.toml
COPY apps/api/app ./app
RUN uv sync --no-dev

CMD ["uv", "run", "--no-dev", "python", "-m", "app.workers.worker_app"]
