FROM node:22-alpine

WORKDIR /app

COPY package.json package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/shared-contracts/package.json packages/shared-contracts/package.json
RUN npm install --workspace apps/web

COPY apps/web apps/web

WORKDIR /app/apps/web
EXPOSE 3000
CMD ["npm", "run", "dev"]
